### ISSUE TITLE
Saving a route as public gives a InvalidFormatException

### ISSUE THREAD

**Issue by smsm1** [conveyal/datatools-manager#24]
When trying to save a route as public, in the hope that it'll then show up in an exported GTFS feed, I get the following exception on the console. This occurs on Safari, Firefox and Chrome.

In Chrome, I can inspect element and change the value of the select from 1 to true, and the error doesn't occur when I save, however this still means that no trips, stops, or stop_times are exported.

```
16:24:47.998 [qtp352346504-22] INFO  c.c.d.manager.persistence.DataStore - /Users/shaunmcdonald/code/datatools-manager-data/mapdb/externalFeedSourceProperties
com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of boolean from String value '1': only "true" or "false" recognized
 at [Source: {"gtfsRouteId":"1","agencyId":"3088eaeb-2e4b-44ed-aac5-3b24e0525457","feedId":"edc577ab-100b-4d26-8673-0126f32b2b14","routeBrandingUrl":null,"publiclyVisible":"1","status":"APPROVED","routeShortName":"H-H","routeLongName":"Har-H","routeDesc":null,"gtfsRouteType":4,"routeUrl":"http://example.com","routeColor":null,"routeTextColor":null,"id":"515c48dc-fe37-452a-bccc-3d84fc5c7599"}; line: 1, column: 141] (through reference chain: com.conveyal.datatools.editor.models.transit.Route["publiclyVisible"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:55)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:883)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseBoolean(StdDeserializer.java:201)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$BooleanDeserializer.deserialize(NumberDeserializers.java:163)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$BooleanDeserializer.deserialize(NumberDeserializers.java:145)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3564)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2580)
	at com.conveyal.datatools.editor.controllers.api.RouteController.updateRoute(RouteController.java:137)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by landonreed** [comment]
Thanks for the bug report @smsm1.

**Comment by smsm1** [comment]
Thanks for the quick fix, that error when saving the route has gone away now.
